export const SIGNUP = "SIGNUP";
export const SIGNUPSUCCESS = "SIGNUP_SUCCESS";
export const LOGINSUCCESS = "LOGIN_SUCCESS"

export const FETCH_FROM_FIREBASE = "FETCH_FROM_FIREBASE";
export const FILTER_SUCCESS = "FILTER_SUCCESS";


export const DONOR_REG_SUCCESS = "DONOR_REG_SUCCESS";
export const FILTER_HOGYA = "FILTER_HOGYA";